export interface Zone {
  id: string
  label: string
}

export interface SentenceExercise {
  mode: 'Positive' | 'Negative' | 'Question'
  hint: string
  zones: Zone[]
  tiles: string[]
  correct: Record<string, string>
  vocabWords: string[]
}

export const SENTENCES_BY_MODULE: Record<number, SentenceExercise[]> = {
  1: [
    {
      mode: 'Positive',
      hint: 'Each letter stands for a word — "A is for Apple"',
      zones: [{ id: 'letter', label: 'LETTER' }, { id: 'verb', label: 'IS FOR' }, { id: 'word', label: 'WORD' }],
      tiles: ['A', 'is for', 'Apple', 'E', 'stands for', 'Egg'],
      correct: { letter: 'A', verb: 'is for', word: 'Apple' },
      vocabWords: ['apple'],
    },
    {
      mode: 'Positive',
      hint: 'Which word starts with this vowel?',
      zones: [{ id: 'letter', label: 'LETTER' }, { id: 'verb', label: 'IS FOR' }, { id: 'word', label: 'WORD' }],
      tiles: ['I', 'is for', 'Ink', 'O', 'stands for', 'Orange'],
      correct: { letter: 'I', verb: 'is for', word: 'Ink' },
      vocabWords: ['ink'],
    },
    {
      mode: 'Positive',
      hint: 'Which letter does this word start with?',
      zones: [{ id: 'word', label: 'WORD' }, { id: 'verb', label: 'STARTS WITH' }, { id: 'letter', label: 'LETTER' }],
      tiles: ['Ball', 'starts with', 'B', 'Cat', 'begins with', 'C'],
      correct: { word: 'Ball', verb: 'starts with', letter: 'B' },
      vocabWords: ['ball'],
    },
    {
      mode: 'Negative',
      hint: '"B is NOT a vowel" — use "is not"',
      zones: [{ id: 'letter', label: 'LETTER' }, { id: 'negative', label: 'IS NOT' }, { id: 'category', label: 'CATEGORY' }],
      tiles: ['B', 'is not', 'a vowel', 'U', 'is', 'a consonant'],
      correct: { letter: 'B', negative: 'is not', category: 'a vowel' },
      vocabWords: ['vowel'],
    },
    {
      mode: 'Question',
      hint: '"Is A a vowel?" — use "Is" to ask a question',
      zones: [{ id: 'helper', label: 'IS' }, { id: 'letter', label: 'LETTER' }, { id: 'category', label: 'CATEGORY' }],
      tiles: ['Is', 'A', 'a vowel', 'Are', 'D', 'a consonant'],
      correct: { helper: 'Is', letter: 'A', category: 'a vowel' },
      vocabWords: ['vowel'],
    },
  ],

  2: [
    {
      mode: 'Positive',
      hint: 'Subject + Verb + Object',
      zones: [{ id: 'subject', label: 'SUBJECT' }, { id: 'verb', label: 'VERB' }, { id: 'object', label: 'OBJECT' }],
      tiles: ['I', 'eat', 'food', 'She', 'drink', 'water'],
      correct: { subject: 'I', verb: 'eat', object: 'food' },
      vocabWords: ['eat', 'food'],
    },
    {
      mode: 'Positive',
      hint: 'Subject + Verb + Object',
      zones: [{ id: 'subject', label: 'SUBJECT' }, { id: 'verb', label: 'VERB' }, { id: 'object', label: 'OBJECT' }],
      tiles: ['She', 'reads', 'books', 'He', 'writes', 'letters'],
      correct: { subject: 'She', verb: 'reads', object: 'books' },
      vocabWords: ['read'],
    },
    {
      mode: 'Positive',
      hint: 'Subject + Verb + Object',
      zones: [{ id: 'subject', label: 'SUBJECT' }, { id: 'verb', label: 'VERB' }, { id: 'object', label: 'OBJECT' }],
      tiles: ['We', 'need', 'water', 'They', 'want', 'food'],
      correct: { subject: 'We', verb: 'need', object: 'water' },
      vocabWords: ['need', 'water'],
    },
    {
      mode: 'Negative',
      hint: 'Subject + NOT + Verb + Object',
      zones: [{ id: 'subject', label: 'SUBJECT' }, { id: 'negative', label: 'NEGATIVE' }, { id: 'verb', label: 'VERB' }, { id: 'object', label: 'OBJECT' }],
      tiles: ['He', 'does not', 'eat', 'meat', 'She', 'do not', 'drink', 'milk'],
      correct: { subject: 'He', negative: 'does not', verb: 'eat', object: 'meat' },
      vocabWords: ['eat'],
    },
    {
      mode: 'Question',
      hint: 'Helper + Subject + Verb + Object + ?',
      zones: [{ id: 'helper', label: '? HELPER' }, { id: 'subject', label: 'SUBJECT' }, { id: 'verb', label: 'VERB' }, { id: 'object', label: 'OBJECT' }],
      tiles: ['Do', 'you', 'like', 'tea', 'Does', 'he', 'want', 'food'],
      correct: { helper: 'Do', subject: 'you', verb: 'like', object: 'tea' },
      vocabWords: ['like'],
    },
  ],

  3: [
    {
      mode: 'Positive',
      hint: 'Subject + Verb + Object',
      zones: [{ id: 'subject', label: 'SUBJECT' }, { id: 'verb', label: 'VERB' }, { id: 'object', label: 'OBJECT' }],
      tiles: ['I', 'am', 'happy', 'She', 'is', 'good'],
      correct: { subject: 'I', verb: 'am', object: 'happy' },
      vocabWords: ['happy', 'good'],
    },
    {
      mode: 'Positive',
      hint: 'Subject + Verb + Object',
      zones: [{ id: 'subject', label: 'SUBJECT' }, { id: 'verb', label: 'VERB' }, { id: 'object', label: 'OBJECT' }],
      tiles: ['He', 'works', 'hard', 'They', 'play', 'outside'],
      correct: { subject: 'He', verb: 'works', object: 'hard' },
      vocabWords: ['work'],
    },
    {
      mode: 'Negative',
      hint: 'Subject + NOT + Verb',
      zones: [{ id: 'subject', label: 'SUBJECT' }, { id: 'negative', label: 'NEGATIVE' }, { id: 'verb', label: 'VERB' }],
      tiles: ['We', 'are not', 'ready', 'They', 'is not', 'happy'],
      correct: { subject: 'We', negative: 'are not', verb: 'ready' },
      vocabWords: ['ready'],
    },
    {
      mode: 'Negative',
      hint: 'Subject + NOT + Verb + Object',
      zones: [{ id: 'subject', label: 'SUBJECT' }, { id: 'negative', label: 'NEGATIVE' }, { id: 'verb', label: 'VERB' }, { id: 'object', label: 'OBJECT' }],
      tiles: ['I', 'do not', 'eat', 'meat', 'She', 'does not', 'drink', 'water'],
      correct: { subject: 'I', negative: 'do not', verb: 'eat', object: 'meat' },
      vocabWords: ['eat'],
    },
    {
      mode: 'Question',
      hint: 'Helper + Subject + Verb + ?',
      zones: [{ id: 'helper', label: '? HELPER' }, { id: 'subject', label: 'SUBJECT' }, { id: 'verb', label: 'VERB' }],
      tiles: ['Is', 'he', 'ready', 'Are', 'they', 'happy'],
      correct: { helper: 'Is', subject: 'he', verb: 'ready' },
      vocabWords: ['ready'],
    },
  ],

  4: [
    {
      mode: 'Positive',
      hint: 'Use a greeting + how are you?',
      zones: [{ id: 'subject', label: 'SUBJECT' }, { id: 'verb', label: 'VERB' }, { id: 'greeting', label: 'GREETING' }],
      tiles: ['I', 'say', 'good morning', 'She', 'says', 'good evening'],
      correct: { subject: 'I', verb: 'say', greeting: 'good morning' },
      vocabWords: ['say', 'morning'],
    },
    {
      mode: 'Positive',
      hint: 'Subject + Verb + Number + Object',
      zones: [{ id: 'subject', label: 'SUBJECT' }, { id: 'verb', label: 'VERB' }, { id: 'number', label: 'NUMBER' }, { id: 'object', label: 'OBJECT' }],
      tiles: ['I', 'have', 'three', 'books', 'She', 'has', 'five', 'pens'],
      correct: { subject: 'I', verb: 'have', number: 'three', object: 'books' },
      vocabWords: ['have', 'three', 'book'],
    },
    {
      mode: 'Positive',
      hint: 'My name is ___ — use this for self-introduction',
      zones: [{ id: 'starter', label: 'MY NAME' }, { id: 'verb', label: 'IS' }, { id: 'name', label: 'NAME' }],
      tiles: ['My name', 'is', 'Ali', 'Her name', 'is called', 'Sara'],
      correct: { starter: 'My name', verb: 'is', name: 'Ali' },
      vocabWords: ['name'],
    },
    {
      mode: 'Question',
      hint: 'What day is today? — asking about the day of the week',
      zones: [{ id: 'helper', label: 'WHAT' }, { id: 'verb', label: 'DAY IS' }, { id: 'subject', label: 'SUBJECT' }],
      tiles: ['What', 'day is', 'today', 'Which', 'month is', 'this'],
      correct: { helper: 'What', verb: 'day is', subject: 'today' },
      vocabWords: ['day', 'today'],
    },
    {
      mode: 'Positive',
      hint: 'Today is ___ — tell someone what day it is',
      zones: [{ id: 'subject', label: 'SUBJECT' }, { id: 'verb', label: 'IS' }, { id: 'day', label: 'DAY' }],
      tiles: ['Today', 'is', 'Friday', 'Tomorrow', 'was', 'Saturday'],
      correct: { subject: 'Today', verb: 'is', day: 'Friday' },
      vocabWords: ['Friday', 'today'],
    },
    {
      mode: 'Positive',
      hint: 'Saying the time: It is ___ o\'clock',
      zones: [{ id: 'subject', label: 'SUBJECT' }, { id: 'verb', label: 'IS' }, { id: 'time', label: 'TIME' }],
      tiles: ['It', 'is', 'three o\'clock', 'The time', 'shows', 'half past four'],
      correct: { subject: 'It', verb: 'is', time: 'three o\'clock' },
      vocabWords: ['time', 'clock'],
    },
    {
      mode: 'Negative',
      hint: 'Subject + NOT + Verb + Object',
      zones: [{ id: 'subject', label: 'SUBJECT' }, { id: 'negative', label: 'NEGATIVE' }, { id: 'verb', label: 'VERB' }, { id: 'phrase', label: 'PHRASE' }],
      tiles: ['I', 'do not', 'forget', 'to say please', 'She', 'does not', 'skip', 'thank you'],
      correct: { subject: 'I', negative: 'do not', verb: 'forget', phrase: 'to say please' },
      vocabWords: ['please', 'forget'],
    },
    {
      mode: 'Question',
      hint: '"Can you please...?" is a very polite way to ask for help',
      zones: [{ id: 'helper', label: 'CAN' }, { id: 'subject', label: 'SUBJECT' }, { id: 'verb', label: 'VERB PHRASE' }, { id: 'object', label: 'OBJECT' }],
      tiles: ['Can', 'you', 'please help', 'me', 'Could', 'they', 'please show', 'us'],
      correct: { helper: 'Can', subject: 'you', verb: 'please help', object: 'me' },
      vocabWords: ['please', 'help'],
    },
  ],

  5: [
    {
      mode: 'Positive',
      hint: 'Subject + am looking for + Object',
      zones: [{ id: 'subject', label: 'SUBJECT' }, { id: 'verb', label: 'VERB PHRASE' }, { id: 'object', label: 'OBJECT' }],
      tiles: ['I', 'am looking for', 'a shirt', 'She', 'is looking for', 'a bag'],
      correct: { subject: 'I', verb: 'am looking for', object: 'a shirt' },
      vocabWords: ['shirt', 'bag'],
    },
    {
      mode: 'Question',
      hint: 'How much + does + Object + cost + ?',
      zones: [{ id: 'starter', label: 'HOW MUCH' }, { id: 'helper', label: 'DOES' }, { id: 'object', label: 'OBJECT' }, { id: 'verb', label: 'VERB' }],
      tiles: ['How much', 'does', 'it', 'cost', 'How many', 'did', 'this', 'count'],
      correct: { starter: 'How much', helper: 'does', object: 'it', verb: 'cost' },
      vocabWords: ['cost'],
    },
    {
      mode: 'Positive',
      hint: 'I would like + to + verb',
      zones: [{ id: 'subject', label: 'SUBJECT' }, { id: 'helper', label: 'WOULD LIKE' }, { id: 'verb', label: 'TO + VERB' }],
      tiles: ['I', 'would like', 'to pay', 'She', 'would like', 'to buy'],
      correct: { subject: 'I', helper: 'would like', verb: 'to pay' },
      vocabWords: ['pay', 'buy'],
    },
    {
      mode: 'Question',
      hint: 'Can + you + give me + Object + ?',
      zones: [{ id: 'helper', label: 'CAN' }, { id: 'subject', label: 'SUBJECT' }, { id: 'verb', label: 'VERB PHRASE' }, { id: 'object', label: 'OBJECT' }],
      tiles: ['Can', 'you', 'give me', 'a discount', 'Could', 'they', 'show me', 'the price'],
      correct: { helper: 'Can', subject: 'you', verb: 'give me', object: 'a discount' },
      vocabWords: ['give', 'discount'],
    },
    {
      mode: 'Positive',
      hint: 'Subject + will + pay + by + method',
      zones: [{ id: 'subject', label: 'SUBJECT' }, { id: 'verb', label: 'WILL PAY' }, { id: 'method', label: 'METHOD' }],
      tiles: ['I', 'will pay', 'by cash', 'She', 'would pay', 'by card'],
      correct: { subject: 'I', verb: 'will pay', method: 'by cash' },
      vocabWords: ['pay'],
    },
  ],

  6: [
    {
      mode: 'Positive',
      hint: 'I have worked in + place + for + time',
      zones: [{ id: 'subject', label: 'SUBJECT' }, { id: 'verb', label: 'VERB PHRASE' }, { id: 'place', label: 'FIELD' }],
      tiles: ['I', 'have worked in', 'sales', 'She', 'has worked in', 'finance'],
      correct: { subject: 'I', verb: 'have worked in', place: 'sales' },
      vocabWords: ['work', 'sales'],
    },
    {
      mode: 'Positive',
      hint: 'I am skilled at + skill',
      zones: [{ id: 'subject', label: 'SUBJECT' }, { id: 'verb', label: 'AM SKILLED AT' }, { id: 'skill', label: 'SKILL' }],
      tiles: ['I', 'am skilled at', 'communication', 'She', 'is skilled at', 'management'],
      correct: { subject: 'I', verb: 'am skilled at', skill: 'communication' },
      vocabWords: ['communication', 'skill'],
    },
    {
      mode: 'Positive',
      hint: 'My goal is to + verb',
      zones: [{ id: 'starter', label: 'MY GOAL' }, { id: 'verb', label: 'IS TO + VERB' }, { id: 'object', label: 'OBJECT' }],
      tiles: ['My goal', 'is to grow', 'professionally', 'Our goal', 'is to lead', 'a team'],
      correct: { starter: 'My goal', verb: 'is to grow', object: 'professionally' },
      vocabWords: ['grow', 'goal'],
    },
    {
      mode: 'Positive',
      hint: 'I would like to join + company',
      zones: [{ id: 'subject', label: 'SUBJECT' }, { id: 'verb', label: 'WOULD LIKE TO JOIN' }, { id: 'object', label: 'COMPANY' }],
      tiles: ['I', 'would like to join', 'your company', 'She', 'wants to join', 'this team'],
      correct: { subject: 'I', verb: 'would like to join', object: 'your company' },
      vocabWords: ['join', 'company'],
    },
    {
      mode: 'Question',
      hint: 'Could + you + tell me + about + Object + ?',
      zones: [{ id: 'helper', label: 'COULD' }, { id: 'subject', label: 'SUBJECT' }, { id: 'verb', label: 'VERB PHRASE' }, { id: 'object', label: 'OBJECT' }],
      tiles: ['Could', 'you', 'tell me about', 'the role', 'Would', 'they', 'show me', 'the office'],
      correct: { helper: 'Could', subject: 'you', verb: 'tell me about', object: 'the role' },
      vocabWords: ['role'],
    },
  ],
}

// ─── Level 2 exercises (Tenses) ──────────────────────────────────────────────
export const SENTENCES_LEVEL_2: Record<number, SentenceExercise[]> = {
  1: [
    {
      mode: 'Positive',
      hint: 'Subject + Verb + Object (Present Simple: daily habits)',
      zones: [{ id: 'subject', label: 'SUBJECT' }, { id: 'verb', label: 'VERB' }, { id: 'object', label: 'OBJECT' }],
      tiles: ['I', 'eat', 'breakfast', 'She', 'reads', 'books'],
      correct: { subject: 'I', verb: 'eat', object: 'breakfast' },
      vocabWords: ['eat', 'breakfast'],
    },
    {
      mode: 'Positive',
      hint: 'He/She/It + Verb+s (Present Simple third person)',
      zones: [{ id: 'subject', label: 'SUBJECT' }, { id: 'verb', label: 'VERB+S' }, { id: 'object', label: 'OBJECT' }],
      tiles: ['He', 'works', 'every day', 'She', 'teaches', 'English'],
      correct: { subject: 'He', verb: 'works', object: 'every day' },
      vocabWords: ['work', 'every day'],
    },
    {
      mode: 'Negative',
      hint: 'I/You/We/They + do not | He/She/It + does not',
      zones: [{ id: 'subject', label: 'SUBJECT' }, { id: 'negative', label: 'NEGATIVE' }, { id: 'verb', label: 'VERB' }],
      tiles: ['I', 'do not', 'like', 'spicy food', 'He', 'does not', 'eat', 'meat'],
      correct: { subject: 'I', negative: 'do not', verb: 'like' },
      vocabWords: ['like'],
    },
    {
      mode: 'Question',
      hint: 'Do + you/we/they | Does + he/she/it + Verb?',
      zones: [{ id: 'helper', label: 'HELPER' }, { id: 'subject', label: 'SUBJECT' }, { id: 'verb', label: 'VERB' }],
      tiles: ['Do', 'you', 'speak', 'English', 'Does', 'she', 'work', 'here'],
      correct: { helper: 'Do', subject: 'you', verb: 'speak' },
      vocabWords: ['speak'],
    },
    {
      mode: 'Positive',
      hint: 'Subject + am/is/are + Verb-ing (Present Continuous)',
      zones: [{ id: 'subject', label: 'SUBJECT' }, { id: 'helper', label: 'AM/IS/ARE' }, { id: 'verb', label: 'VERB+ING' }],
      tiles: ['She', 'is', 'studying', 'They', 'are', 'playing'],
      correct: { subject: 'She', helper: 'is', verb: 'studying' },
      vocabWords: ['study', 'now'],
    },
  ],
  2: [
    {
      mode: 'Positive',
      hint: 'Subject + Verb+ed (Past Simple regular verb)',
      zones: [{ id: 'subject', label: 'SUBJECT' }, { id: 'verb', label: 'PAST VERB' }, { id: 'time', label: 'TIME' }],
      tiles: ['I', 'worked', 'yesterday', 'She', 'played', 'last week'],
      correct: { subject: 'I', verb: 'worked', time: 'yesterday' },
      vocabWords: ['yesterday'],
    },
    {
      mode: 'Positive',
      hint: 'Subject + irregular past verb (go → went, eat → ate)',
      zones: [{ id: 'subject', label: 'SUBJECT' }, { id: 'verb', label: 'PAST VERB' }, { id: 'object', label: 'OBJECT' }],
      tiles: ['She', 'went', 'to school', 'He', 'ate', 'biryani'],
      correct: { subject: 'She', verb: 'went', object: 'to school' },
      vocabWords: ['went', 'school'],
    },
    {
      mode: 'Negative',
      hint: 'Subject + did not + Verb (base form)',
      zones: [{ id: 'subject', label: 'SUBJECT' }, { id: 'negative', label: 'DID NOT' }, { id: 'verb', label: 'BASE VERB' }],
      tiles: ['I', 'did not', 'go', 'She', 'did not', 'eat'],
      correct: { subject: 'I', negative: 'did not', verb: 'go' },
      vocabWords: ['go'],
    },
    {
      mode: 'Question',
      hint: 'Did + Subject + Verb (base form)?',
      zones: [{ id: 'helper', label: 'DID' }, { id: 'subject', label: 'SUBJECT' }, { id: 'verb', label: 'VERB' }],
      tiles: ['Did', 'you', 'eat', 'lunch', 'Did', 'she', 'call', 'you'],
      correct: { helper: 'Did', subject: 'you', verb: 'eat' },
      vocabWords: ['eat', 'lunch'],
    },
    {
      mode: 'Positive',
      hint: 'I/She/He + went/came/saw — common irregular past verbs',
      zones: [{ id: 'subject', label: 'SUBJECT' }, { id: 'verb', label: 'VERB' }, { id: 'object', label: 'OBJECT' }],
      tiles: ['He', 'bought', 'a phone', 'She', 'wrote', 'a letter'],
      correct: { subject: 'He', verb: 'bought', object: 'a phone' },
      vocabWords: ['bought', 'phone'],
    },
  ],
  3: [
    {
      mode: 'Positive',
      hint: 'Subject + will + Verb (base form) — future decision',
      zones: [{ id: 'subject', label: 'SUBJECT' }, { id: 'helper', label: 'WILL' }, { id: 'verb', label: 'VERB' }],
      tiles: ['I', 'will', 'study', 'She', 'will', 'call'],
      correct: { subject: 'I', helper: 'will', verb: 'study' },
      vocabWords: ['study', 'tomorrow'],
    },
    {
      mode: 'Negative',
      hint: 'Subject + will not (won\'t) + Verb',
      zones: [{ id: 'subject', label: 'SUBJECT' }, { id: 'negative', label: 'WILL NOT' }, { id: 'verb', label: 'VERB' }],
      tiles: ['I', "will not", 'be late', 'She', "won't", 'forget'],
      correct: { subject: 'I', negative: 'will not', verb: 'be late' },
      vocabWords: ['late'],
    },
    {
      mode: 'Positive',
      hint: 'Subject + am/is/are + going to + Verb (planned future)',
      zones: [{ id: 'subject', label: 'SUBJECT' }, { id: 'helper', label: 'AM GOING TO' }, { id: 'verb', label: 'VERB' }],
      tiles: ['I', 'am going to', 'study', 'She', 'is going to', 'visit'],
      correct: { subject: 'I', helper: 'am going to', verb: 'study' },
      vocabWords: ['study', 'plan'],
    },
    {
      mode: 'Question',
      hint: 'Will + Subject + Verb?',
      zones: [{ id: 'helper', label: 'WILL' }, { id: 'subject', label: 'SUBJECT' }, { id: 'verb', label: 'VERB' }],
      tiles: ['Will', 'you', 'come', 'tomorrow', 'Will', 'she', 'pass', 'the exam'],
      correct: { helper: 'Will', subject: 'you', verb: 'come' },
      vocabWords: ['come'],
    },
    {
      mode: 'Positive',
      hint: 'Use "a" before consonant sounds, "an" before vowel sounds',
      zones: [{ id: 'article', label: 'ARTICLE' }, { id: 'noun', label: 'NOUN' }],
      tiles: ['a', 'book', 'an', 'apple', 'the', 'sun'],
      correct: { article: 'a', noun: 'book' },
      vocabWords: ['article'],
    },
  ],
  4: [
    {
      mode: 'Positive',
      hint: 'How much does it cost? — asking the price',
      zones: [{ id: 'subject', label: 'SUBJECT' }, { id: 'verb', label: 'VERB PHRASE' }, { id: 'object', label: 'OBJECT' }],
      tiles: ['I', 'am looking for', 'a shirt', 'She', 'is looking for', 'shoes'],
      correct: { subject: 'I', verb: 'am looking for', object: 'a shirt' },
      vocabWords: ['looking for', 'shirt'],
    },
    {
      mode: 'Question',
      hint: 'How much does it cost? — asking the price',
      zones: [{ id: 'starter', label: 'HOW MUCH' }, { id: 'helper', label: 'DOES' }, { id: 'object', label: 'OBJECT' }, { id: 'verb', label: 'VERB' }],
      tiles: ['How much', 'does', 'this', 'cost', 'How many', 'did', 'they', 'pay'],
      correct: { starter: 'How much', helper: 'does', object: 'this', verb: 'cost' },
      vocabWords: ['cost'],
    },
    {
      mode: 'Positive',
      hint: 'I would like to order — making a polite request',
      zones: [{ id: 'subject', label: 'SUBJECT' }, { id: 'helper', label: 'WOULD LIKE TO' }, { id: 'verb', label: 'VERB' }],
      tiles: ['I', 'would like to', 'order', 'She', 'would like to', 'pay'],
      correct: { subject: 'I', helper: 'would like to', verb: 'order' },
      vocabWords: ['order', 'polite'],
    },
    {
      mode: 'Question',
      hint: 'Can you give me...? — asking for help',
      zones: [{ id: 'helper', label: 'CAN' }, { id: 'subject', label: 'SUBJECT' }, { id: 'verb', label: 'VERB PHRASE' }, { id: 'object', label: 'OBJECT' }],
      tiles: ['Can', 'you', 'give me', 'a discount', 'Could', 'they', 'show me', 'the menu'],
      correct: { helper: 'Can', subject: 'you', verb: 'give me', object: 'a discount' },
      vocabWords: ['discount'],
    },
    {
      mode: 'Positive',
      hint: 'Nice to meet you — self-introduction phrase',
      zones: [{ id: 'phrase', label: 'PHRASE' }, { id: 'subject', label: 'SUBJECT' }, { id: 'name', label: 'NAME' }],
      tiles: ['My name', 'is', 'Ali', 'Her name', 'was', 'Sara'],
      correct: { phrase: 'My name', subject: 'is', name: 'Ali' },
      vocabWords: ['name', 'meet'],
    },
  ],
  5: [
    {
      mode: 'Positive',
      hint: 'Review: I eat (Present), I ate (Past), I will eat (Future)',
      zones: [{ id: 'subject', label: 'SUBJECT' }, { id: 'verb', label: 'PAST VERB' }, { id: 'object', label: 'OBJECT' }],
      tiles: ['I', 'went', 'to school', 'She', 'ate', 'biryani'],
      correct: { subject: 'I', verb: 'went', object: 'to school' },
      vocabWords: ['went', 'school'],
    },
    {
      mode: 'Positive',
      hint: 'I am going to study tonight — planned future',
      zones: [{ id: 'subject', label: 'SUBJECT' }, { id: 'helper', label: 'AM GOING TO' }, { id: 'verb', label: 'VERB' }],
      tiles: ['I', 'am going to', 'study', 'She', 'is going to', 'travel'],
      correct: { subject: 'I', helper: 'am going to', verb: 'study' },
      vocabWords: ['study', 'plan'],
    },
    {
      mode: 'Negative',
      hint: 'She does not — Present Simple negative with he/she/it',
      zones: [{ id: 'subject', label: 'SUBJECT' }, { id: 'negative', label: 'NEGATIVE' }, { id: 'verb', label: 'VERB' }],
      tiles: ['She', 'does not', 'speak', 'He', 'did not', 'go'],
      correct: { subject: 'She', negative: 'does not', verb: 'speak' },
      vocabWords: ['speak'],
    },
    {
      mode: 'Question',
      hint: 'Did you...? / Do you...? / Will you...? — three tense questions',
      zones: [{ id: 'helper', label: 'HELPER' }, { id: 'subject', label: 'SUBJECT' }, { id: 'verb', label: 'VERB' }],
      tiles: ['Did', 'you', 'eat', 'Do', 'they', 'work', 'Will', 'she', 'come'],
      correct: { helper: 'Did', subject: 'you', verb: 'eat' },
      vocabWords: ['eat'],
    },
    {
      mode: 'Positive',
      hint: 'My English is getting better — present continuous for gradual change',
      zones: [{ id: 'subject', label: 'SUBJECT' }, { id: 'verb', label: 'IS GETTING' }, { id: 'adjective', label: 'ADJECTIVE' }],
      tiles: ['My English', 'is getting', 'better', 'His skills', 'are becoming', 'stronger'],
      correct: { subject: 'My English', verb: 'is getting', adjective: 'better' },
      vocabWords: ['better', 'improve'],
    },
  ],
}

// ─── Level 3 exercises (12 Tenses, Vocab, Reading) ───────────────────────────
export const SENTENCES_LEVEL_3: Record<number, SentenceExercise[]> = {
  1: [
    {
      mode: 'Positive',
      hint: 'I have + V3 — Present Perfect (the experience matters)',
      zones: [{ id: 'subject', label: 'SUBJECT' }, { id: 'helper', label: 'HAVE' }, { id: 'verb', label: 'PAST PARTICIPLE' }],
      tiles: ['I', 'have', 'finished', 'She', 'has', 'arrived'],
      correct: { subject: 'I', helper: 'have', verb: 'finished' },
      vocabWords: ['finished', 'already'],
    },
    {
      mode: 'Positive',
      hint: 'I was + Verb-ing when... — Past Continuous',
      zones: [{ id: 'subject', label: 'SUBJECT' }, { id: 'helper', label: 'WAS' }, { id: 'verb', label: 'VERB+ING' }],
      tiles: ['I', 'was', 'sleeping', 'She', 'was', 'cooking'],
      correct: { subject: 'I', helper: 'was', verb: 'sleeping' },
      vocabWords: ['sleeping', 'when'],
    },
    {
      mode: 'Negative',
      hint: 'I have not + V3 — Present Perfect Negative',
      zones: [{ id: 'subject', label: 'SUBJECT' }, { id: 'negative', label: 'HAVE NOT' }, { id: 'verb', label: 'PAST PARTICIPLE' }],
      tiles: ['I', 'have not', 'eaten', 'She', 'has not', 'arrived'],
      correct: { subject: 'I', negative: 'have not', verb: 'eaten' },
      vocabWords: ['eaten', 'yet'],
    },
    {
      mode: 'Question',
      hint: 'Have you ever + V3? — asking about life experience',
      zones: [{ id: 'helper', label: 'HAVE' }, { id: 'subject', label: 'SUBJECT' }, { id: 'adverb', label: 'EVER' }, { id: 'verb', label: 'PAST PARTICIPLE' }],
      tiles: ['Have', 'you', 'ever', 'visited', 'Has', 'she', 'already', 'finished'],
      correct: { helper: 'Have', subject: 'you', adverb: 'ever', verb: 'visited' },
      vocabWords: ['ever', 'visited'],
    },
    {
      mode: 'Positive',
      hint: 'She had + V3 + before he arrived — Past Perfect',
      zones: [{ id: 'subject', label: 'SUBJECT' }, { id: 'helper', label: 'HAD' }, { id: 'verb', label: 'PAST PARTICIPLE' }],
      tiles: ['She', 'had', 'left', 'He', 'had', 'eaten'],
      correct: { subject: 'She', helper: 'had', verb: 'left' },
      vocabWords: ['left', 'before'],
    },
  ],
  2: [
    {
      mode: 'Positive',
      hint: 'He feels ___ — using emotion vocabulary',
      zones: [{ id: 'subject', label: 'SUBJECT' }, { id: 'verb', label: 'VERB' }, { id: 'adjective', label: 'EMOTION WORD' }],
      tiles: ['He', 'feels', 'grateful', 'She', 'feels', 'frustrated'],
      correct: { subject: 'He', verb: 'feels', adjective: 'grateful' },
      vocabWords: ['grateful', 'feeling'],
    },
    {
      mode: 'Positive',
      hint: 'Knowledge + is/opens/empowers — core vocabulary sentence',
      zones: [{ id: 'subject', label: 'SUBJECT' }, { id: 'verb', label: 'VERB' }, { id: 'object', label: 'OBJECT' }],
      tiles: ['Knowledge', 'is', 'power', 'Education', 'opens', 'doors'],
      correct: { subject: 'Knowledge', verb: 'is', object: 'power' },
      vocabWords: ['knowledge', 'power'],
    },
    {
      mode: 'Positive',
      hint: 'She recovered from her illness — health vocabulary',
      zones: [{ id: 'subject', label: 'SUBJECT' }, { id: 'verb', label: 'VERB' }, { id: 'phrase', label: 'PHRASE' }],
      tiles: ['She', 'recovered', 'quickly', 'He', 'suffered', 'greatly'],
      correct: { subject: 'She', verb: 'recovered', phrase: 'quickly' },
      vocabWords: ['recovered', 'illness'],
    },
    {
      mode: 'Negative',
      hint: 'The Wi-Fi does not work — technology vocabulary',
      zones: [{ id: 'subject', label: 'SUBJECT' }, { id: 'negative', label: 'DOES NOT' }, { id: 'verb', label: 'VERB' }],
      tiles: ['The Wi-Fi', 'does not', 'work', 'The app', 'did not', 'download'],
      correct: { subject: 'The Wi-Fi', negative: 'does not', verb: 'work' },
      vocabWords: ['Wi-Fi', 'technology'],
    },
    {
      mode: 'Question',
      hint: 'Do you feel... ? — asking about emotions',
      zones: [{ id: 'helper', label: 'DO' }, { id: 'subject', label: 'SUBJECT' }, { id: 'verb', label: 'FEEL' }, { id: 'adjective', label: 'EMOTION' }],
      tiles: ['Do', 'you', 'feel', 'confident', 'Does', 'she', 'feel', 'ready'],
      correct: { helper: 'Do', subject: 'you', verb: 'feel', adjective: 'confident' },
      vocabWords: ['confident'],
    },
  ],
  3: [
    {
      mode: 'Positive',
      hint: 'There was a ___ who — story opening',
      zones: [{ id: 'starter', label: 'THERE WAS' }, { id: 'article', label: 'A' }, { id: 'noun', label: 'PERSON' }],
      tiles: ['There was', 'a', 'farmer', 'There were', 'some', 'students'],
      correct: { starter: 'There was', article: 'a', noun: 'farmer' },
      vocabWords: ['farmer', 'story'],
    },
    {
      mode: 'Positive',
      hint: 'He worked hard every day — past tense in a story',
      zones: [{ id: 'subject', label: 'SUBJECT' }, { id: 'verb', label: 'PAST VERB' }, { id: 'adverb', label: 'ADVERB' }],
      tiles: ['He', 'worked', 'hard', 'She', 'studied', 'diligently'],
      correct: { subject: 'He', verb: 'worked', adverb: 'hard' },
      vocabWords: ['worked', 'hard'],
    },
    {
      mode: 'Positive',
      hint: 'In the end, he felt proud — story conclusion',
      zones: [{ id: 'time', label: 'TIME' }, { id: 'subject', label: 'SUBJECT' }, { id: 'verb', label: 'FELT' }, { id: 'emotion', label: 'EMOTION' }],
      tiles: ['In the end', 'he', 'felt', 'proud', 'Finally', 'she', 'felt', 'grateful'],
      correct: { time: 'In the end', subject: 'he', verb: 'felt', emotion: 'proud' },
      vocabWords: ['proud', 'finally'],
    },
    {
      mode: 'Positive',
      hint: 'She never gave up — expressing determination',
      zones: [{ id: 'subject', label: 'SUBJECT' }, { id: 'adverb', label: 'NEVER' }, { id: 'verb', label: 'VERB' }],
      tiles: ['She', 'never', 'gave up', 'He', 'always', 'tried'],
      correct: { subject: 'She', adverb: 'never', verb: 'gave up' },
      vocabWords: ['never', 'determination'],
    },
    {
      mode: 'Question',
      hint: 'What happened next? — asking about story events',
      zones: [{ id: 'question', label: 'WHAT' }, { id: 'verb', label: 'HAPPENED' }, { id: 'adverb', label: 'WHEN' }],
      tiles: ['What', 'happened', 'next', 'Who', 'arrived', 'first'],
      correct: { question: 'What', verb: 'happened', adverb: 'next' },
      vocabWords: ['happened', 'next'],
    },
  ],
  4: [
    {
      mode: 'Positive',
      hint: 'According to the passage — comprehension phrase',
      zones: [{ id: 'phrase', label: 'ACCORDING TO' }, { id: 'subject', label: 'SUBJECT' }, { id: 'verb', label: 'VERB' }],
      tiles: ['According to the passage', 'Sara', 'is a doctor', 'Based on the text', 'he', 'works hard'],
      correct: { phrase: 'According to the passage', subject: 'Sara', verb: 'is a doctor' },
      vocabWords: ['according to', 'passage'],
    },
    {
      mode: 'Positive',
      hint: 'The main idea is ___ — summarising a reading',
      zones: [{ id: 'subject', label: 'MAIN IDEA' }, { id: 'verb', label: 'IS' }, { id: 'idea', label: 'IDEA' }],
      tiles: ['The main idea', 'is', 'hard work', 'The topic', 'is about', 'education'],
      correct: { subject: 'The main idea', verb: 'is', idea: 'hard work' },
      vocabWords: ['main idea', 'topic'],
    },
    {
      mode: 'Question',
      hint: 'What is the main idea? — comprehension question',
      zones: [{ id: 'question', label: 'WHAT' }, { id: 'verb', label: 'IS' }, { id: 'subject', label: 'SUBJECT' }],
      tiles: ['What', 'is', 'the main idea', 'Who', 'wrote', 'this passage'],
      correct: { question: 'What', verb: 'is', subject: 'the main idea' },
      vocabWords: ['main idea'],
    },
    {
      mode: 'Positive',
      hint: 'In conclusion — ending a summary',
      zones: [{ id: 'starter', label: 'IN CONCLUSION' }, { id: 'subject', label: 'SUBJECT' }, { id: 'verb', label: 'VERB' }],
      tiles: ['In conclusion', 'the author', 'believes', 'In summary', 'the story', 'shows'],
      correct: { starter: 'In conclusion', subject: 'the author', verb: 'believes' },
      vocabWords: ['conclusion', 'author'],
    },
    {
      mode: 'Positive',
      hint: 'She has been working — Present Perfect Continuous',
      zones: [{ id: 'subject', label: 'SUBJECT' }, { id: 'helper', label: 'HAS BEEN' }, { id: 'verb', label: 'VERB+ING' }],
      tiles: ['She', 'has been', 'working', 'He', 'has been', 'studying'],
      correct: { subject: 'She', helper: 'has been', verb: 'working' },
      vocabWords: ['working', 'duration'],
    },
  ],
  5: [
    {
      mode: 'Positive',
      hint: 'I have + V3 — review of Present Perfect',
      zones: [{ id: 'subject', label: 'SUBJECT' }, { id: 'helper', label: 'HAVE' }, { id: 'verb', label: 'PAST PARTICIPLE' }],
      tiles: ['I', 'have', 'learned', 'She', 'has', 'improved'],
      correct: { subject: 'I', helper: 'have', verb: 'learned' },
      vocabWords: ['learned', 'improved'],
    },
    {
      mode: 'Positive',
      hint: 'I can now use all 12 tenses — ability statement',
      zones: [{ id: 'subject', label: 'SUBJECT' }, { id: 'helper', label: 'CAN NOW' }, { id: 'verb', label: 'VERB' }],
      tiles: ['I', 'can now', 'use', 'She', 'could now', 'speak'],
      correct: { subject: 'I', helper: 'can now', verb: 'use' },
      vocabWords: ['can', 'ability'],
    },
    {
      mode: 'Negative',
      hint: 'She was not sleeping when he called — past continuous negative',
      zones: [{ id: 'subject', label: 'SUBJECT' }, { id: 'negative', label: 'WAS NOT' }, { id: 'verb', label: 'VERB+ING' }],
      tiles: ['She', 'was not', 'sleeping', 'He', 'were not', 'working'],
      correct: { subject: 'She', negative: 'was not', verb: 'sleeping' },
      vocabWords: ['sleeping'],
    },
    {
      mode: 'Question',
      hint: 'Have you ever...? — asking about life experience',
      zones: [{ id: 'helper', label: 'HAVE' }, { id: 'subject', label: 'SUBJECT' }, { id: 'adverb', label: 'EVER' }, { id: 'verb', label: 'VERB' }],
      tiles: ['Have', 'you', 'ever', 'read', 'Has', 'she', 'already', 'finished'],
      correct: { helper: 'Have', subject: 'you', adverb: 'ever', verb: 'read' },
      vocabWords: ['ever', 'experience'],
    },
    {
      mode: 'Positive',
      hint: 'In conclusion, I believe — Level 3 review phrase',
      zones: [{ id: 'starter', label: 'IN CONCLUSION' }, { id: 'subject', label: 'SUBJECT' }, { id: 'verb', label: 'BELIEVE' }],
      tiles: ['In conclusion', 'I', 'believe', 'In summary', 'she', 'thinks'],
      correct: { starter: 'In conclusion', subject: 'I', verb: 'believe' },
      vocabWords: ['conclusion', 'believe'],
    },
  ],
}

// ─── Level 4 exercises (Writing & Speaking) ───────────────────────────────────
export const SENTENCES_LEVEL_4: SentenceExercise[] = [
  {
    mode: 'Positive',
    hint: 'Furthermore + main clause — linking word for addition',
    zones: [{ id: 'linker', label: 'LINKER' }, { id: 'subject', label: 'SUBJECT' }, { id: 'verb', label: 'VERB' }],
    tiles: ['Furthermore', 'this', 'shows', 'Moreover', 'English', 'helps'],
    correct: { linker: 'Furthermore', subject: 'this', verb: 'shows' },
    vocabWords: ['furthermore', 'linking word'],
  },
  {
    mode: 'Positive',
    hint: 'Although + clause, main clause — contrast connector',
    zones: [{ id: 'linker', label: 'ALTHOUGH' }, { id: 'clause', label: 'CLAUSE' }, { id: 'main', label: 'MAIN CLAUSE' }],
    tiles: ['Although', 'it was hard', 'she continued', 'Even though', 'he was tired', 'he studied'],
    correct: { linker: 'Although', clause: 'it was hard', main: 'she continued' },
    vocabWords: ['although', 'contrast'],
  },
  {
    mode: 'Positive',
    hint: 'Therefore + result clause — showing cause and effect',
    zones: [{ id: 'linker', label: 'THEREFORE' }, { id: 'subject', label: 'SUBJECT' }, { id: 'verb', label: 'VERB' }],
    tiles: ['Therefore', 'I', 'studied harder', 'Thus', 'she', 'improved'],
    correct: { linker: 'Therefore', subject: 'I', verb: 'studied harder' },
    vocabWords: ['therefore', 'result'],
  },
  {
    mode: 'Positive',
    hint: 'Respected Sir, I am writing to — formal letter opening',
    zones: [{ id: 'salutation', label: 'SALUTATION' }, { id: 'subject', label: 'SUBJECT' }, { id: 'verb', label: 'AM WRITING TO' }],
    tiles: ['Respected Sir', 'I', 'am writing to request', 'Dear Madam', 'She', 'is writing to inform'],
    correct: { salutation: 'Respected Sir', subject: 'I', verb: 'am writing to request' },
    vocabWords: ['respected', 'request'],
  },
  {
    mode: 'Positive',
    hint: 'Not only... but also — adding a strong second point',
    zones: [{ id: 'starter', label: 'NOT ONLY' }, { id: 'point1', label: 'POINT 1' }, { id: 'addition', label: 'BUT ALSO' }, { id: 'point2', label: 'POINT 2' }],
    tiles: ['Not only', 'is she smart', 'but also', 'hardworking', 'Not only', 'did he pass', 'but also', 'excelled'],
    correct: { starter: 'Not only', point1: 'is she smart', addition: 'but also', point2: 'hardworking' },
    vocabWords: ['not only', 'but also'],
  },
]

// ─── Level 5 exercises (Advanced Grammar) ────────────────────────────────────
export const SENTENCES_LEVEL_5: SentenceExercise[] = [
  {
    mode: 'Positive',
    hint: 'If + Present Simple, will + Verb — Type 1 Conditional (real/possible)',
    zones: [{ id: 'condition', label: 'IF CLAUSE' }, { id: 'result', label: 'RESULT' }],
    tiles: ['If you study hard', 'you will pass', 'If she practises daily', 'she will improve'],
    correct: { condition: 'If you study hard', result: 'you will pass' },
    vocabWords: ['conditional', 'possible'],
  },
  {
    mode: 'Positive',
    hint: 'If + Past Simple, would + Verb — Type 2 Conditional (imaginary)',
    zones: [{ id: 'condition', label: 'IF CLAUSE' }, { id: 'result', label: 'WOULD CLAUSE' }],
    tiles: ['If I had time', 'I would travel', 'If she were free', 'she would help'],
    correct: { condition: 'If I had time', result: 'I would travel' },
    vocabWords: ['imaginary', 'would'],
  },
  {
    mode: 'Positive',
    hint: 'Object + was/were + V3 — Passive Voice',
    zones: [{ id: 'object', label: 'OBJECT' }, { id: 'helper', label: 'WAS' }, { id: 'verb', label: 'PAST PARTICIPLE' }],
    tiles: ['The letter', 'was', 'written', 'The report', 'was', 'submitted'],
    correct: { object: 'The letter', helper: 'was', verb: 'written' },
    vocabWords: ['passive', 'written'],
  },
  {
    mode: 'Positive',
    hint: 'He gave up / She looked up — phrasal verb sentence',
    zones: [{ id: 'subject', label: 'SUBJECT' }, { id: 'verb', label: 'PHRASAL VERB' }, { id: 'object', label: 'OBJECT' }],
    tiles: ['She', 'gave up', 'the plan', 'He', 'looked up', 'the word'],
    correct: { subject: 'She', verb: 'gave up', object: 'the plan' },
    vocabWords: ['gave up', 'phrasal verb'],
  },
  {
    mode: 'Positive',
    hint: 'The purpose of today\'s meeting is to ___ — business English opener',
    zones: [{ id: 'starter', label: 'THE PURPOSE OF' }, { id: 'subject', label: 'THIS MEETING' }, { id: 'verb', label: 'IS TO' }, { id: 'action', label: 'ACTION' }],
    tiles: ['The purpose of', 'this meeting', 'is to', 'review targets', 'The goal of', 'today', 'is to', 'make decisions'],
    correct: { starter: 'The purpose of', subject: 'this meeting', verb: 'is to', action: 'review targets' },
    vocabWords: ['purpose', 'meeting'],
  },
]

// ─── Level 6 exercises (Professional English) ────────────────────────────────
export const SENTENCES_LEVEL_6: SentenceExercise[] = [
  {
    mode: 'Positive',
    hint: 'I am writing to apply for — professional email phrase',
    zones: [{ id: 'subject', label: 'SUBJECT' }, { id: 'verb', label: 'AM WRITING TO' }, { id: 'object', label: 'APPLY FOR' }],
    tiles: ['I', 'am writing to apply for', 'the position', 'She', 'is writing to request', 'a meeting'],
    correct: { subject: 'I', verb: 'am writing to apply for', object: 'the position' },
    vocabWords: ['apply for', 'position'],
  },
  {
    mode: 'Positive',
    hint: 'My greatest strength is my ___ — interview answer',
    zones: [{ id: 'starter', label: 'MY GREATEST' }, { id: 'noun', label: 'STRENGTH IS' }, { id: 'object', label: 'MY...' }],
    tiles: ['My greatest', 'strength is', 'my dedication', 'My biggest', 'strength is', 'my teamwork'],
    correct: { starter: 'My greatest', noun: 'strength is', object: 'my dedication' },
    vocabWords: ['strength', 'dedication'],
  },
  {
    mode: 'Positive',
    hint: 'In my opinion + main argument — IELTS essay phrase',
    zones: [{ id: 'phrase', label: 'IN MY OPINION' }, { id: 'subject', label: 'SUBJECT' }, { id: 'verb', label: 'VERB' }],
    tiles: ['In my opinion', 'education', 'is essential', 'In my view', 'technology', 'helps everyone'],
    correct: { phrase: 'In my opinion', subject: 'education', verb: 'is essential' },
    vocabWords: ['opinion', 'IELTS'],
  },
  {
    mode: 'Positive',
    hint: 'I look forward to hearing from you — formal closing phrase',
    zones: [{ id: 'subject', label: 'SUBJECT' }, { id: 'verb', label: 'LOOK FORWARD TO' }, { id: 'object', label: 'OBJECT' }],
    tiles: ['I', 'look forward to', 'hearing from you', 'She', 'looks forward to', 'the interview'],
    correct: { subject: 'I', verb: 'look forward to', object: 'hearing from you' },
    vocabWords: ['look forward to', 'formal'],
  },
  {
    mode: 'Positive',
    hint: 'If I had known, I would have started — Type 3 Conditional (regret)',
    zones: [{ id: 'condition', label: 'IF I HAD' }, { id: 'verb1', label: 'PAST PARTICIPLE' }, { id: 'result', label: 'WOULD HAVE' }],
    tiles: ['If I had', 'known', 'I would have started earlier', 'If she had', 'studied', 'she would have passed'],
    correct: { condition: 'If I had', verb1: 'known', result: 'I would have started earlier' },
    vocabWords: ['regret', 'conditional'],
  },
]

// ─── Level-aware lookup ───────────────────────────────────────────────────────

const LEVEL_SENTENCES: Record<number, (module: number) => SentenceExercise[]> = {
  1: (module) => SENTENCES_BY_MODULE[module] ?? SENTENCES_BY_MODULE[2],
  2: (module) => SENTENCES_LEVEL_2[module] ?? SENTENCES_LEVEL_2[1],
  3: (module) => SENTENCES_LEVEL_3[module] ?? SENTENCES_LEVEL_3[1],
  4: () => SENTENCES_LEVEL_4,
  5: () => SENTENCES_LEVEL_5,
  6: () => SENTENCES_LEVEL_6,
}

export function getSentences(module: number, level = 1): SentenceExercise[] {
  const resolver = LEVEL_SENTENCES[level] ?? LEVEL_SENTENCES[1]
  return resolver(module)
}
